goog.provide('symlog.cljs.app.elements');
goog.require('cljs.core');
symlog.cljs.app.elements.FPS = 15;
symlog.cljs.app.elements.narratorSpinner = goog.dom.getElement("narratorSpinner");
symlog.cljs.app.elements.mainSpinner = goog.dom.getElement("spinner");
symlog.cljs.app.elements.canvas = goog.dom.getElement("canvas");
symlog.cljs.app.elements.context = goog.dom.getElement("canvas").getContext("2d");
symlog.cljs.app.elements.paintFrame = (new Image());
symlog.cljs.app.elements.goodcopSrc = "../video/goodcop.webm";
symlog.cljs.app.elements.mainVidSrc = "../video/policeaction.webm";
symlog.cljs.app.elements.narratorDiv = goog.dom.getElement("narratorDiv");
symlog.cljs.app.elements.narratorVid = goog.dom.getElement("narratorVid");
symlog.cljs.app.elements.narratorPlayTouchArea = goog.dom.getElement("narratorPlayTouchArea");
symlog.cljs.app.elements.narratorDisableTouchArea = goog.dom.getElement("narratorDisableTouchArea");
symlog.cljs.app.elements.narratorPlayButton = goog.dom.getElement("narratorPlayButton");
symlog.cljs.app.elements.narratorTOCsDiv = goog.dom.getElement("narratorTOCs");
symlog.cljs.app.elements.narratorDisableButton = goog.dom.getElement("narratorDisableButton");
symlog.cljs.app.elements.narratorSkipButton = goog.dom.getElement("narratorSkipButton");
symlog.cljs.app.elements.narratorSkipTouchArea = goog.dom.getElement("narratorSkipTouchArea");
symlog.cljs.app.elements.mainVideo = goog.dom.getElement("mainVideo");
symlog.cljs.app.elements.mainVideoPlayButton = goog.dom.getElement("mainVideoPlayButton");
symlog.cljs.app.elements.mainVideoPlayTouchArea = goog.dom.getElement("mainVideoPlayTouchArea");
symlog.cljs.app.elements.narratorScenes = goog.dom.getElementsByClass("nscene");
symlog.cljs.app.elements.controlButton = goog.dom.getElement("controlButton");
symlog.cljs.app.elements.tocCanvas = goog.dom.getElement("tocCanvas");
symlog.cljs.app.elements.controllerTouchArea = goog.dom.getElement("controllerTouchArea");
