goog.provide('symlog.cljs.app.sequences.sq3');
goog.require('cljs.core');
goog.require('symlog.cljs.util');
goog.require('symlog.cljs.app');
goog.require('symlog.cljs.util');
goog.require('symlog.cljs.app');
goog.require('symlog.cljs.animation.functions');
symlog.cljs.app.sequences.sq3.init = (function init(){
symlog.cljs.app.sequences.sq3.actions = cljs.core.PersistentHashMap.fromArrays([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],[cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",symlog.cljs.util.synchronize.call(null,0,(function (){
symlog.cljs.app.elements.call(null,"\uFDD0:context").clearRect(0,0,symlog.cljs.app.elements.call(null,"\uFDD0:canvas").width,symlog.cljs.app.elements.call(null,"\uFDD0:canvas").height);
return symlog.cljs.app.elements.call(null,"\uFDD0:mainVideo").className = "dark";
}),0,(new symlog.cljs.animation.functions.animate_path(symlog.cljs.app.elements.call(null,"\uFDD0:narrator"),(1000 / 25),.2,1,false,[cljs.core.str("M 420,210 C 704.65414,195.76729 870,120 870,120")].join(''))).fire,0,(function (){
symlog.cljs.app.elements.call(null,"\uFDD0:mainVideo").src = symlog.cljs.app.elements.call(null,"\uFDD0:mainVidSrc");
symlog.cljs.app.elements.call(null,"\uFDD0:mainVideo").className = "faded";
return controller.playNarrator.call(null);
}))], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",(new symlog.cljs.animation.functions.paint_frames(symlog.cljs.app.elements.call(null,"\uFDD0:paintFrame"),cljs.core.deref.call(null,symlog.cljs.app.elements.call(null,"\uFDD0:seq2FrameBuffer")).slice(0,9),(1000 / 20))).fire], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",(new symlog.cljs.animation.functions.paint_frames(symlog.cljs.app.elements.call(null,"\uFDD0:paintFrame"),cljs.core.deref.call(null,symlog.cljs.app.elements.call(null,"\uFDD0:seq2FrameBuffer")).slice(10,18),(1000 / 20))).fire], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",(new symlog.cljs.animation.functions.paint_frames(symlog.cljs.app.elements.call(null,"\uFDD0:paintFrame"),cljs.core.deref.call(null,symlog.cljs.app.elements.call(null,"\uFDD0:seq2FrameBuffer")).slice(19,26),(1000 / 20))).fire], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",(function actions(){
return symlog.cljs.app.elements.call(null,"\uFDD0:context").clearRect(0,0,symlog.cljs.app.elements.call(null,"\uFDD0:canvas").width,symlog.cljs.app.elements.call(null,"\uFDD0:canvas").height);
})], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",(new symlog.cljs.animation.functions.paint_frames(symlog.cljs.app.elements.call(null,"\uFDD0:paintFrame"),cljs.core.deref.call(null,symlog.cljs.app.elements.call(null,"\uFDD0:seq2FrameBuffer")).slice(27,55),(1000 / 20))).fire], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",(new symlog.cljs.animation.functions.paint_frames(symlog.cljs.app.elements.call(null,"\uFDD0:paintFrame"),cljs.core.deref.call(null,symlog.cljs.app.elements.call(null,"\uFDD0:seq2FrameBuffer")).slice(55,78),(1000 / 20))).fire], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",(new symlog.cljs.animation.functions.paint_frames(symlog.cljs.app.elements.call(null,"\uFDD0:paintFrame"),cljs.core.deref.call(null,symlog.cljs.app.elements.call(null,"\uFDD0:seq2FrameBuffer")).slice(79,116),(1000 / 20))).fire], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",(new symlog.cljs.animation.functions.paint_frames(symlog.cljs.app.elements.call(null,"\uFDD0:paintFrame"),cljs.core.deref.call(null,symlog.cljs.app.elements.call(null,"\uFDD0:seq2FrameBuffer")).slice(117,161),(1000 / 20))).fire], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",(function actions(){
return symlog.cljs.app.elements.call(null,"\uFDD0:context").clearRect(0,0,symlog.cljs.app.elements.call(null,"\uFDD0:canvas").width,symlog.cljs.app.elements.call(null,"\uFDD0:canvas").height);
})], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",(new symlog.cljs.animation.functions.paint_frames(symlog.cljs.app.elements.call(null,"\uFDD0:paintFrame"),cljs.core.deref.call(null,symlog.cljs.app.elements.call(null,"\uFDD0:seq2FrameBuffer")).slice(162,167),(1000 / 20))).fire], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",(new symlog.cljs.animation.functions.paint_frames(symlog.cljs.app.elements.call(null,"\uFDD0:paintFrame"),cljs.core.deref.call(null,symlog.cljs.app.elements.call(null,"\uFDD0:seq2FrameBuffer")).slice(168,177),(1000 / 20))).fire], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",(new symlog.cljs.animation.functions.paint_frames(symlog.cljs.app.elements.call(null,"\uFDD0:paintFrame"),cljs.core.deref.call(null,symlog.cljs.app.elements.call(null,"\uFDD0:seq2FrameBuffer")).slice(178,198),(1000 / 20))).fire], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",(function actions(){
return symlog.cljs.app.elements.call(null,"\uFDD0:context").clearRect(0,0,symlog.cljs.app.elements.call(null,"\uFDD0:canvas").width,symlog.cljs.app.elements.call(null,"\uFDD0:canvas").height);
})], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",(new symlog.cljs.animation.functions.paint_frames(symlog.cljs.app.elements.call(null,"\uFDD0:paintFrame"),cljs.core.deref.call(null,symlog.cljs.app.elements.call(null,"\uFDD0:seq2FrameBuffer")).slice(199,207),(1000 / 20))).fire], true),cljs.core.PersistentArrayMap.fromArray(["\uFDD0:enabled",true,"\uFDD0:range",cljs.core.range.call(null,0,100),"\uFDD0:triggered",false,"\uFDD0:trigger",symlog.cljs.util.synchronize.call(null,0,(function (){
return symlog.cljs.app.elements.call(null,"\uFDD0:context").clearRect(0,0,symlog.cljs.app.elements.call(null,"\uFDD0:canvas").width,symlog.cljs.app.elements.call(null,"\uFDD0:canvas").height);
}),0,(function (){
return controller.pauseNarrator.call(null);
}),0,(new symlog.cljs.animation.functions.animate_path(symlog.cljs.app.elements.call(null,"\uFDD0:narrator"),(1000 / 20),.2,.5,false,[cljs.core.str("M 870,120 C 602.16633,60.481405 265,52 265,52")].join(''))).fire)], true)]);
});
