(ns symlog.cljs.app.elements)

(def FPS                          15)
(def narratorSpinner              (goog.dom.getElement "narratorSpinner"))
(def mainSpinner                  (goog.dom.getElement "spinner"))
(def canvas                       (goog.dom.getElement "canvas"))
(def context                      (. (goog.dom.getElement "canvas") getContext "2d"))
(def paintFrame                   (js.Image.))
(def goodcopSrc                   "../video/goodcop.webm")
(def mainVidSrc                   "../video/policeaction.webm")
(def narratorDiv                  (goog.dom.getElement  "narratorDiv"))
(def narratorVid                  (goog.dom.getElement "narratorVid"))
(def narratorPlayTouchArea        (goog.dom.getElement "narratorPlayTouchArea"))
(def narratorDisableTouchArea     (goog.dom.getElement "narratorDisableTouchArea"))
(def narratorPlayButton           (goog.dom.getElement "narratorPlayButton"))
(def narratorTOCsDiv              (goog.dom.getElement "narratorTOCs"))
(def narratorDisableButton        (goog.dom.getElement "narratorDisableButton"))
(def narratorSkipButton           (goog.dom.getElement "narratorSkipButton"))
(def narratorSkipTouchArea        (goog.dom.getElement "narratorSkipTouchArea"))
(def mainVideo                    (goog.dom.getElement "mainVideo"))
(def mainVideoPlayButton          (goog.dom.getElement "mainVideoPlayButton"))
(def mainVideoPlayTouchArea       (goog.dom.getElement "mainVideoPlayTouchArea"))
(def narratorScenes               (goog.dom.getElementsByClass "nscene"))         
(def controlButton                (goog.dom.getElement "controlButton") )
(def tocCanvas                    (goog.dom.getElement "tocCanvas"))
(def controllerTouchArea          (goog.dom.getElement "controllerTouchArea"))
